id: I1CABAFA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T09:58:11+00:00'
last_modified: '2022-06-08T16:53:14.310630+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4912
  title: ཤུགས་ལྡན་བེའུ་བུམ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    24AA:
      image_group_id: I1KG4914
      title: ''
      total_pages: 764
      order: 1
      base_file: 24AA.txt
    84BE:
      image_group_id: I1KG4915
      title: ''
      total_pages: 734
      order: 2
      base_file: 84BE.txt
    4B37:
      image_group_id: I1KG4916
      title: ''
      total_pages: 734
      order: 3
      base_file: 4B37.txt
    '6568':
      image_group_id: I1KG4917
      title: ''
      total_pages: 766
      order: 4
      base_file: 6568.txt
    0B6E:
      image_group_id: I1KG4918
      title: ''
      total_pages: 662
      order: 5
      base_file: 0B6E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
