id: I1CABAFA3
legacy_id: P010698
ocr_import_info:
  bdrc_scan_id: W1KG4912
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T09:53:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:06:03.597208+00:00'
last_modified: 2022-09-01 01:07:42.147228
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4912
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4912
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤུགས་ལྡན་བེའུ་བུམ། ༼གློག་ཀླད་པར་མ།༽
statistics:
  ocr_word_mean_confidence_index: 0.8548578748430222
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG4918:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4918
      total_pages: 662
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG4918.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8510572374983462
    legacy_id: v005
  I1KG4916:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4916
      total_pages: 734
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG4916.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8357993712016413
    legacy_id: v003
  I1KG4917:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4917
      total_pages: 766
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG4917.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9122763937945205
    legacy_id: v004
  I1KG4914:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4914
      total_pages: 764
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4914.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8474796082292646
    legacy_id: v001
  I1KG4915:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4915
      total_pages: 734
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4915.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.831322658464051
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
